version: '3.8'

services:
  
  jira:
    container_name: jira
    image: atlassian/jira-software:8
    volumes:
      - ~/volumes/atlassian/jira:/var/atlassian/application-data/jira
    environment:
       ATL_PROXY_NAME: jira.fd
       ATL_PROXY_PORT: 443
       ATL_TOMCAT_SCHEME: https
       ATL_TOMCAT_SECURE: "true"
    networks:
      - devsecopsnet
    depends_on:
      - db

  confluence:
    container_name: confluence
    image: atlassian/confluence-server:7
    volumes:
      - ~/volumes/atlassian/confluence:/var/atlassian/application-data/confluence
    environment: 
      ATL_PROXY_NAME: confluence.fd
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: "true"
    networks:
      - devsecopsnet
    depends_on:
      - db

  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:7
    ports:
     - "7999:7999"
    volumes:
      - ~/volumes/atlassian/bitbucket:/var/atlassian/application-data/bitbucket
    environment: 
      SERVER_PROXY_NAME: bitbucket.fd
      SERVER_PROXY_PORT: 443
      SERVER_SCHEME: https
      SERVER_SECURE: "true"
    networks:
      - devsecopsnet
    depends_on:
      - db

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - ~/volumes/jenkins/home:/var/jenkins_home
    networks:
      - devsecopsnet  

  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.30.0
    volumes:
      - ~/volumes/nexus/nexus-data:/nexus-data
    networks:
      - devsecopsnet

  db:
    container_name: postgres10
    image: postgres:10
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
      - ~/volumes/postgres/data/10:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerQWER
    networks:
      - devsecopsnet

  nginx: 
    container_name: nginx 
    image: nginx:1.17 
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf 
     - ./config/nginx/ssl/:/etc/nginx/ssl
    depends_on: 
     - jira 
     - confluence 
     - bitbucket 
     - jenkins
     - nexus
    ports: 
     - "80:80" 
     - "443:443"
    networks: 
     - devsecopsnet 

networks:
  devsecopsnet:
