version: '3.8'

services:
  
  jira:
    container_name: jira
    image: atlassian/jira-software:8
    volumes:
      - jira-ssl:/var/atlassian/application-data/jira
    environment:
       ATL_PROXY_NAME: jira.fires.division
       ATL_PROXY_PORT: 443
       ATL_TOMCAT_SCHEME: https
       ATL_TOMCAT_SECURE: "true"
    networks:
      - devsecopsnet-ssl
    depends_on:
      - db

  confluence:
    container_name: confluence
    image: atlassian/confluence-server:7
    volumes:
      - confluence-ssl:/var/atlassian/application-data/confluence
    environment: 
      ATL_PROXY_NAME: confluence.fires.division
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: "true"
    networks:
      - devsecopsnet-ssl
    depends_on:
      - db

  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:7
    ports:
     - "7999:7999"
    volumes:
      - bitbucket-ssl:/var/atlassian/application-data/bitbucket
    environment: 
      SERVER_PROXY_NAME: bitbucket.fires.division
      SERVER_PROXY_PORT: 443
      SERVER_SCHEME: https
      SERVER_SECURE: "true"
    networks:
      - devsecopsnet-ssl
    depends_on:
      - db

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins-ssl:/var/jenkins_home
    networks:
      - devsecopsnet-ssl  

  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.37.3
    volumes:
      - nexus-ssl:/nexus-data
    networks:
      - devsecopsnet-ssl

  db:
    container_name: postgres10
    image: postgres:10
    volumes:
      - ../config/postgres:/docker-entrypoint-initdb.d
      - postgres-ssl:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerQWER
    networks:
      - devsecopsnet-ssl

  nginx: 
    container_name: nginx 
    image: nginx:1.17 
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf 
     - ./config/nginx/ssl/:/etc/nginx/ssl
    depends_on: 
     - jira 
     - confluence 
     - bitbucket 
     - jenkins
     - nexus
    ports: 
     - "8090:8090" 
     - "8443:8443"
    networks: 
     - devsecopsnet-ssl 

networks:
  devsecopsnet-ssl:

volumes:
  jira-ssl:
  confluence-ssl:
  bitbucket-ssl:
  jenkins-ssl:
  postgres-ssl:
  nexus-ssl: