version: '3.8'

services:
  
  jira:
    container_name: jira
    image: atlassian/jira-software:8
    volumes:
      - jira:/var/atlassian/application-data/jira
    environment:
       ATL_PROXY_NAME: jira.fires.division
       ATL_PROXY_PORT: 8080
       ATL_TOMCAT_SCHEME: http 
    networks:
      - devsecopsnet
    depends_on:
      - db

  confluence:
    container_name: confluence
    image: atlassian/confluence-server:7
    volumes:
      - confluence:/var/atlassian/application-data/confluence
    environment: 
      ATL_PROXY_NAME: confluence.fires.division
      ATL_PROXY_PORT: 8080
      ATL_TOMCAT_SCHEME: http
    networks:
      - devsecopsnet
    depends_on:
      - db

  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:7
    ports:
     - "7999:7999"
    volumes:
      - bitbucket:/var/atlassian/application-data/bitbucket
    environment: 
      SERVER_PROXY_NAME: bitbucket.fires.division
      SERVER_PROXY_PORT: 8080
      SERVER_SCHEME: http 
    networks:
      - devsecopsnet
    depends_on:
      - db

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    #ports:
    #  - "8081:8081"
    #  - "50000:50000"
    networks:
      - devsecopsnet  
    #environment:
    #  JENKINS_OPTS: --httpPort=8080

  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.37.3
    volumes:
      - nexus:/nexus-data
    #ports:
    #  - 8081:8081
    networks:
      - devsecopsnet

  db:
    container_name: postgres10
    image: postgres:10
    #ports:
    #  - "5432:5432"
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerQWER
    networks:
      - devsecopsnet

  nginx: 
    container_name: nginx 
    image: nginx:1.17 
    volumes:
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on: 
     - jira 
     - confluence 
     - bitbucket 
     - jenkins
     - nexus
    ports: 
     - "8080:8080"
    # - "8081:8081"
    networks: 
      - devsecopsnet
         
networks:
  devsecopsnet:

volumes:
  jira:
    external: true
  confluence:
    external: true
  bitbucket:
    external: true
  jenkins:
    external: true
  postgres:
    external: true
  nexus:
    external: true
